const WALK_INDEX = 0;
const CAR_INDEX = 1;
const RAIL_INDEX = 2;
const SUB_INDEX = 3;
const TRAIN_INDEX = 4;
const TRAM_INDEX = 5;
const BUS_INDEX = 6;

export { WALK_INDEX, CAR_INDEX, RAIL_INDEX, SUB_INDEX, TRAIN_INDEX, TRAM_INDEX, BUS_INDEX };